name: script test

on: [push]

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    name: Build and run docker image
    steps:
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Run arm64 emulation
          run: docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3 
          
        - name: Build docker image
          working-directory: Pythonscript
          run: docker build -t zasasas20/lifewatch . 
        
        - name: Push docker image
          working-directory: Pythonscript
          run: |
                echo "${{ secrets.DOCKERPASS }}" | docker login -u "zasasas20" --password-stdin
                docker push zasasas20/lifewatch:latest
