name: script test

on: [push]

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    name: Build and run docker image
    steps:

        - name: Check out repo
          uses: actions/checkout@v4.1.6

        - name: Build docker image
          run: docker build -t zasasas20/lifewatch . 
        
        - name: Push docker image
          run: |
                echo "${{ secrets.DOCKERPASS }}" | docker login -u "zasasas20" --password-stdin
                docker push zasasas20/lifewatch:latest
